/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IExternalOracle,
  IExternalOracleInterface,
} from "../IExternalOracle";

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IExternalOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IExternalOracleInterface {
    return new utils.Interface(_abi) as IExternalOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExternalOracle {
    return new Contract(address, _abi, signerOrProvider) as IExternalOracle;
  }
}
