/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPriceOracleWrapper,
  IPriceOracleWrapperInterface,
} from "../IPriceOracleWrapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdPrice",
        type: "uint256",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPriceOracleWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceOracleWrapperInterface {
    return new utils.Interface(_abi) as IPriceOracleWrapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPriceOracleWrapper {
    return new Contract(address, _abi, signerOrProvider) as IPriceOracleWrapper;
  }
}
