/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface Erc721ContractFactoryInterface extends ethers.utils.Interface {
  functions: {
    "_cloneAddressIds(address)": FunctionFragment;
    "_cloneAddresses(uint256)": FunctionFragment;
    "_cloneExists(address)": FunctionFragment;
    "_pausedCloneIndex(uint256)": FunctionFragment;
    "_pausedList(uint256)": FunctionFragment;
    "_prices(address)": FunctionFragment;
    "_proxyDetails(address)": FunctionFragment;
    "_tokenIdCounter()": FunctionFragment;
    "_unpausedCloneIndex(uint256)": FunctionFragment;
    "_unpausedList(uint256)": FunctionFragment;
    "consumeNft(uint256,address)": FunctionFragment;
    "createClone(string,string,uint256,uint256)": FunctionFragment;
    "implementation()": FunctionFragment;
    "mint(address,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setImplementation(address)": FunctionFragment;
    "totalPaused()": FunctionFragment;
    "totalUnpaused()": FunctionFragment;
    "transferEth(uint256,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_cloneAddressIds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_cloneAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_cloneExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_pausedCloneIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_pausedList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "_prices", values: [string]): string;
  encodeFunctionData(
    functionFragment: "_proxyDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_tokenIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_unpausedCloneIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_unpausedList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "consumeNft",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createClone",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUnpaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferEth",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "_cloneAddressIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_cloneAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_cloneExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_pausedCloneIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_pausedList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_prices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_proxyDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_tokenIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_unpausedCloneIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_unpausedList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "consumeNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createClone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalUnpaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "CreatedNewCloneContract(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatedNewCloneContract"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type CreatedNewCloneContractEvent = TypedEvent<
  [string, BigNumber] & { contractAddress: string; price: BigNumber }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class Erc721ContractFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: Erc721ContractFactoryInterface;

  functions: {
    _cloneAddressIds(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _cloneAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _cloneExists(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    _pausedCloneIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _pausedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _prices(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    _proxyDetails(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        Name: string;
        Symbol: string;
        Description: string;
        Uri: string;
      }
    >;

    _tokenIdCounter(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _value: BigNumber }>;

    _unpausedCloneIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _unpausedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    consumeNft(
      _tokenId: BigNumberish,
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createClone(
      _name: string,
      _symbol: string,
      _maxSupply: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    implementation(overrides?: CallOverrides): Promise<[string]>;

    mint(
      _to: string,
      _cloneAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setImplementation(
      _implementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalPaused(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalUnpaused(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferEth(
      _value: BigNumberish,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _cloneAddressIds(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  _cloneAddresses(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  _cloneExists(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  _pausedCloneIndex(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _pausedList(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _prices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  _proxyDetails(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string] & {
      Name: string;
      Symbol: string;
      Description: string;
      Uri: string;
    }
  >;

  _tokenIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

  _unpausedCloneIndex(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _unpausedList(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  consumeNft(
    _tokenId: BigNumberish,
    _cloneAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createClone(
    _name: string,
    _symbol: string,
    _maxSupply: BigNumberish,
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  implementation(overrides?: CallOverrides): Promise<string>;

  mint(
    _to: string,
    _cloneAddress: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    _cloneAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setImplementation(
    _implementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalPaused(overrides?: CallOverrides): Promise<BigNumber>;

  totalUnpaused(overrides?: CallOverrides): Promise<BigNumber>;

  transferEth(
    _value: BigNumberish,
    _recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    _cloneAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _cloneAddressIds(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _cloneAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    _cloneExists(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    _pausedCloneIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _pausedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _prices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    _proxyDetails(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        Name: string;
        Symbol: string;
        Description: string;
        Uri: string;
      }
    >;

    _tokenIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

    _unpausedCloneIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _unpausedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    consumeNft(
      _tokenId: BigNumberish,
      _cloneAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createClone(
      _name: string,
      _symbol: string,
      _maxSupply: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    implementation(overrides?: CallOverrides): Promise<string>;

    mint(
      _to: string,
      _cloneAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(_cloneAddress: string, overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setImplementation(
      _implementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    totalPaused(overrides?: CallOverrides): Promise<BigNumber>;

    totalUnpaused(overrides?: CallOverrides): Promise<BigNumber>;

    transferEth(
      _value: BigNumberish,
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(_cloneAddress: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "CreatedNewCloneContract(address,uint256)"(
      contractAddress?: string | null,
      price?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { contractAddress: string; price: BigNumber }
    >;

    CreatedNewCloneContract(
      contractAddress?: string | null,
      price?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { contractAddress: string; price: BigNumber }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    _cloneAddressIds(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _cloneAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _cloneExists(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    _pausedCloneIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _pausedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _prices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    _proxyDetails(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    _tokenIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

    _unpausedCloneIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _unpausedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    consumeNft(
      _tokenId: BigNumberish,
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createClone(
      _name: string,
      _symbol: string,
      _maxSupply: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      _to: string,
      _cloneAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setImplementation(
      _implementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalPaused(overrides?: CallOverrides): Promise<BigNumber>;

    totalUnpaused(overrides?: CallOverrides): Promise<BigNumber>;

    transferEth(
      _value: BigNumberish,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _cloneAddressIds(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _cloneAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _cloneExists(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _pausedCloneIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _pausedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _prices(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _proxyDetails(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _tokenIdCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _unpausedCloneIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _unpausedList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    consumeNft(
      _tokenId: BigNumberish,
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createClone(
      _name: string,
      _symbol: string,
      _maxSupply: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    implementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mint(
      _to: string,
      _cloneAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setImplementation(
      _implementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalUnpaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferEth(
      _value: BigNumberish,
      _recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      _cloneAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
