/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ContractFactoryStorage,
  ContractFactoryStorageInterface,
} from "../ContractFactoryStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "_cloneAddresses",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "_cloneExists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "_tokenIdCounter",
    outputs: [
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalPaused",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalUnpaused",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610326806100206000396000f3fe608060405234801561001057600080fd5b50600436106100565760003560e01c8062eea8a21461005b57806315347be4146100795780632bf7dcc4146100a95780637367d9e0146100c757806384c4bd4b146100f7575b600080fd5b610063610115565b604051610070919061025f565b60405180910390f35b610093600480360381019061008e91906101d3565b61011b565b6040516100a09190610229565b60405180910390f35b6100b161014e565b6040516100be919061025f565b60405180910390f35b6100e160048036038101906100dc91906101aa565b610154565b6040516100ee9190610244565b60405180910390f35b6100ff610174565b60405161010c919061025f565b60405180910390f35b60035481565b60016020528060005260406000206000915054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60045481565b60026020528060005260406000206000915054906101000a900460ff1681565b60008060000154905081565b60008135905061018f816102c2565b92915050565b6000813590506101a4816102d9565b92915050565b6000602082840312156101bc57600080fd5b60006101ca84828501610180565b91505092915050565b6000602082840312156101e557600080fd5b60006101f384828501610195565b91505092915050565b6102058161027a565b82525050565b6102148161028c565b82525050565b610223816102b8565b82525050565b600060208201905061023e60008301846101fc565b92915050565b6000602082019050610259600083018461020b565b92915050565b6000602082019050610274600083018461021a565b92915050565b600061028582610298565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b6102cb8161027a565b81146102d657600080fd5b50565b6102e2816102b8565b81146102ed57600080fd5b5056fea2646970667358221220b69e313f1627ddfe481bd1c5825a3869d320a1a7663bda8791f460b02b1ba2d564736f6c63430008040033";

export class ContractFactoryStorage__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractFactoryStorage> {
    return super.deploy(overrides || {}) as Promise<ContractFactoryStorage>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ContractFactoryStorage {
    return super.attach(address) as ContractFactoryStorage;
  }
  connect(signer: Signer): ContractFactoryStorage__factory {
    return super.connect(signer) as ContractFactoryStorage__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ContractFactoryStorageInterface {
    return new utils.Interface(_abi) as ContractFactoryStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ContractFactoryStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ContractFactoryStorage;
  }
}
